services:
  app:
    build: .
    container_name: arena_one_app
    env_file:
      - .env.production
    restart: always
    ports:
      - "3000:3000"
    networks:
      - arenaone-network
    volumes:
      - arenaone_storage:/app/storage

  nginx:
    image: nginx:alpine
    container_name: arena_one_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - arenaone_storage:/app/storage
    depends_on:
      - app
    restart: always

networks:
  arenaone-network:
    external: true

volumes:
  arenaone_storage:
    name: arenaone_storage
